.MODEL SMALL
.STACK
.DATA
	msg1 DB 10,13,"Enter first number:$"
	msg2 DB 10,13,"Enter second number:$"
	msg3 DB 10,13,"Result :$"
.CODE

	MOV DX,OFFSET msg1					;OUTPUT MSG1
	MOV AH,09H
	INT 21H

	MOV AH,01H							;INPUT NUMBER1,THE CONTENT IS STORED IN AL BIT
	INT 21H
	SUB AL,'0'							;CONVERTING ASCII TO BCD

	MOV BL,AL							;STORING 1ST NUMBER IN BL

	MOV DX,OFFSET msg2					;OUTPUT MSG2
	MOV AH,09H
	INT 21H

	MOV AH,01H							;INPUT 2ND NUMBER
	INT 21H

	SUB AL,'0'							;ASCII TO BCD CONVERSION

	MOV AH,00H

	ADD AL,BL							;AL=AL+BL
	AAA									;SETS HIGHER ORDER BIT IF CARRY IS GENERATED (ADJUST AFTER ADDITION)

	ADD AL,'0'							;BCD TO ASCII CONVERSION
	ADD AH,'0'

	MOV BX,AX							;RESULT IS STORED IN BX

	MOV DX,OFFSET msg3					;OUTPUT MSG1
	MOV AH,09H
	INT 21H

	MOV DL,BH							;OUTPUT HIGHER ORDER BITS
	MOV AH,02H
	INT 21H

	MOV DL,BL							;OUTPUT LOWER ORDER BITS
	MOV AH,02H
	INT 21H



END
