.MODEL SMALL
.STACK
.DATA
	MSG1 DB 10,13,"Enter 1st number:$"
	MSG2 DB 10,13,"Enter 2nd number:$"
	MSG3 DB 10,13,"RESULT:$"
	MSG4 DB "-$"
.CODE
	;.STARTUP
	MOV CL,00H
	MOV DX,OFFSET MSG1			;OUTPUT MSG1
	MOV AH,09H
	INT 21H

	MOV AH,01H					;INPUT 1ST NUMBER
	INT 21H

	SUB AL,'0'					;ASCII TO BCD CONVERSION

	MOV BL,AL					;MOVE FIRST NUMBER TO BL

	MOV DX,OFFSET MSG2			;OUTPUT MSG2
	MOV AH,09H
	INT 21H

	MOV AH,01H					;INPUT 2ND NUMBER
	INT 21H

	SUB AL,'0'					;ASCII TO BCD
	.IF AL<BL
		XCHG AL,BL					;EXCHANGE CONTENTS OF AL AND BL
		MOV CL,01H
	.ENDIF

	SUB AL,BL					;AL=2ND NUM-1ST NUM

	ADD AL,'0'					;BCD TO ASCII

	MOV BL,AL					;RESULT IN BL

	MOV DX,OFFSET MSG3			;OUTPUT MSG3
	MOV AH,09H
	INT 21H

	.IF CL==00H
		MOV DX,OFFSET MSG4			;OUTPUT MSG3
		MOV AH,09H
		INT 21H
	.ENDIF

	MOV DL,BL					;OUTPUT RESULT
	MOV AH,02H
	INT 21H

	.EXIT
END
